name: 'Delete workflow runs'
description: 'An action to delete workflow runs in a repository.'
author: 'Bright Ran'
on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: 3

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: ActionsRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.token }}
          repository: ${{ secrets.repository }}
          retain_days: ${{ secrets.retain_days }}
inputs:
  token:
    description: 'The token used to authenticate.'
    required: true
    default: ${{ github.token }}

  repository:
    description: 'The name of the repository.'
    required: true
    default: ${{ github.repository }}

  retain_days:
    description: 'The number of days.'
    required: true
    default: 3

  keep_minimum_runs:
    description: 'The minimum runs to keep for each workflow.'
    required: true
    default: 6

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'delete'
  color: 'red'
