name: 'Delete workflow runs'
on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: 3

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: ActionsRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.token }}
          repository: ${{ secrets.repository }}
          retain_days: ${{ secrets.retain_days }}

